name: Build CI

on:
  push:
    branches:
      - 'kafka-poc'       # PoC main branch
      - '[0-9]+.[0-9]+.x' # Release branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches:
      - 'kafka-poc'       # PoC main branch
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: "snapshot"
      publish-container: ${{ github.ref == 'refs/heads/kafka-poc' }}
    secrets:
      registry-0-usr: ${{ github.repository_owner }}
      registry-0-psw: ${{ secrets.GITHUB_TOKEN }}
